imports:
    - { resource: config.yml }

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    channels: ['command']
    handlers:
         # Use fingers_crossed to buffer until error level reaches
        error_buffer:
            type: fingers_crossed
            action_level: error
            handler: all_logging
         # Group handler to direct logs to multiple destinations. Order file logging first to ensure error is logged even if db is not available
        all_logging:
            type: group
            members: [file_logging, console, database_logging]
        file_logging:
            type: stream
            path: '%kernel.logs_dir%/ui.log'
            level: '%csweb_log_level%'
            channels: ['!command']
        console:
            type: console
            process_psr_3_messages: false
        database_logging:
            type: service
            id: cspro_monolog_handler
            channels: ['!command']
        blob_break_logging:
            type: rotating_file
            path: '%kernel.logs_dir%/cases_process.log'
            level: '%csweb_process_cases_log_level%'
            channels: ["command"]
